site_name: PyMoe

site_url: https://rlalpha49.github.io/AniLinkPy

nav:
  - Home: index.md

theme:
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    view: material/eye
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
  features:
    - search
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - content.action.view

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/AniLinkPy]
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            merge_init_into_class: true
            heading_level: 3
            show_if_no_docstring: true
            docstring_options:
              ignore_init_summary: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

repo_url: https://github.com/RLAlpha49/AniLinkPy

repo_name: RLAlpha49/AniLinkPy

copyright: Copyright &copy; 2024 RLAlpha49 under the MIT License

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RLAlpha49