[project]
name = "AniLinkPy"
version = "1.0.0"
description = "API wrapper for AniManga sites such as Anilist, MyAnimeList, Kitsu."
authors = [{ name = "RLAlpha49", email = "alexpettigrew29@gmail.com"}]
readme = "README.md"
requires-python = ">3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry]
name = "AniLinkPy"
version = "1.0.0"
description = "API wrapper for AniManga sites such as Anilist, MyAnimeList, Kitsu."
authors = ["RLAlpha49"]
readme = "README.md"
license = "MIT"
packages = [{ include = "anilinkpy" }]

[tool.poetry.group.documentation]
optional = true

[tool.poetry.group.cleaning]
optional = true

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"

[tool.poetry.group.documentation.dependencies]
mkdocs = "1.5.*"
mkdocs-material = "9.5.*"
mkdocstrings = { version = "0.24.*", extras = ['python'] }
mkdocs-git-revision-date-localized-plugin = "*"

[tool.poetry.dev-dependencies]
python-dotenv = "*"

[tool.poetry.group.cleaning.dependencies]
black = "*"
isort = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 90

[tool.black]
line-length = 90