[project]
name = "AniLinkPy"
version = "1.0.0"
description = "API wrapper for AniManga sites such as Anilist, MyAnimeList, Kitsu."
authors = [{ name = "RLAlpha49", email = "alexpettigrew29@gmail.com"}]
readme = "README.md"
requires-python = ">3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry]
name = "AniLinkPy"
version = "1.0.0"
description = "API wrapper for AniManga sites such as Anilist, MyAnimeList, Kitsu."
authors = ["RLAlpha49"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"