---
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'
          cache: 'npm'
      - run: npm ci
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}